import { Injectable } from '@nestjs/common';
import { AuditLog } from '@prisma/client';
import { PrismaService } from '../prisma';

/**
 * Audit action types for consistent logging.
 */
export enum AuditAction {
    // Auth actions
    USER_LOGIN = 'USER_LOGIN',
    USER_LOGOUT = 'USER_LOGOUT',
    USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
    USER_REGISTERED = 'USER_REGISTERED',
    DEVICE_ID_BOUND = 'DEVICE_ID_BOUND',
    DEVICE_ID_MISMATCH = 'DEVICE_ID_MISMATCH',

    // User actions
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DEACTIVATED = 'USER_DEACTIVATED',
    USER_ACTIVATED = 'USER_ACTIVATED',
    USER_APPROVED = 'USER_APPROVED',
    USER_REJECTED = 'USER_REJECTED',
    PROFILE_PHOTO_UPDATED = 'PROFILE_PHOTO_UPDATED',

    // Task actions
    TASK_CREATED = 'TASK_CREATED',
    TASK_ASSIGNED = 'TASK_ASSIGNED',
    TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
    TASK_MARKED_SUSPICIOUS = 'TASK_MARKED_SUSPICIOUS',
    TASK_COMPLETED = 'TASK_COMPLETED',

    // Event actions
    EVENT_UPLOADED = 'EVENT_UPLOADED',
    EVENT_REJECTED_DUPLICATE = 'EVENT_REJECTED_DUPLICATE',
    EVENT_REJECTED_TASK_LOCKED = 'EVENT_REJECTED_TASK_LOCKED',
}

/**
 * Parameters for creating an audit log entry.
 */
export interface CreateAuditLogParams {
    userId?: string | null;
    action: string;
    entityType: string;
    entityId?: string | null;
    ipAddress?: string | null;
}

/**
 * Audit Logs Service.
 * Handles creation and retrieval of audit log entries.
 * 
 * CRITICAL: This service only provides INSERT and SELECT operations.
 * UPDATE and DELETE are intentionally NOT implemented.
 */
@Injectable()
export class AuditLogsService {
    constructor(
        private readonly db: PrismaService,
    ) { }

    /**
     * Create a new audit log entry.
     * Timestamp is generated server-side automatically by Prisma.
     * 
     * @param params - Audit log parameters
     * @returns Created audit log entry
     */
    async create(params: CreateAuditLogParams): Promise<AuditLog> {
        return this.db.auditLog.create({
            data: {
                user_id: params.userId ?? null,
                action: params.action,
                entity_type: params.entityType,
                entity_id: params.entityId ?? null,
                ip_address: params.ipAddress ?? null,
                // created_at is auto-generated by Prisma
            },
        });
    }

    /**
     * Convenience method for logging actions with consistent format.
     */
    async log(
        action: AuditAction | string,
        entityType: string,
        entityId: string | null,
        userId: string | null,
        ipAddress: string | null,
    ): Promise<AuditLog> {
        return this.create({
            userId,
            action,
            entityType,
            entityId,
            ipAddress,
        });
    }

    /**
     * Get all audit logs for admin viewing.
     * Results are ordered by created_at descending (newest first).
     * 
     * @param limit - Maximum number of records to return
     * @param offset - Number of records to skip for pagination
     */
    async findAll(limit = 100, offset = 0): Promise<{ data: AuditLog[]; total: number; hasMore: boolean }> {
        const [data, total] = await Promise.all([
            this.db.auditLog.findMany({
                orderBy: { created_at: 'desc' },
                take: limit,
                skip: offset,
            }),
            this.db.auditLog.count(),
        ]);

        return {
            data,
            total,
            hasMore: offset + data.length < total,
        };
    }

    /**
     * Get audit logs for a specific entity.
     */
    async findByEntity(entityType: string, entityId: string): Promise<AuditLog[]> {
        return this.db.auditLog.findMany({
            where: { entity_type: entityType, entity_id: entityId },
            orderBy: { created_at: 'desc' },
        });
    }

    /**
     * Get audit logs for a specific user.
     */
    async findByUser(userId: string): Promise<AuditLog[]> {
        return this.db.auditLog.findMany({
            where: { user_id: userId },
            orderBy: { created_at: 'desc' },
        });
    }
}
