import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { AuditLog } from './entities/audit-log.entity';

/**
 * Audit action types for consistent logging.
 */
export enum AuditAction {
    // Auth actions
    USER_LOGIN = 'USER_LOGIN',
    USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
    DEVICE_ID_BOUND = 'DEVICE_ID_BOUND',
    DEVICE_ID_MISMATCH = 'DEVICE_ID_MISMATCH',

    // User actions
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DEACTIVATED = 'USER_DEACTIVATED',

    // Task actions
    TASK_CREATED = 'TASK_CREATED',
    TASK_ASSIGNED = 'TASK_ASSIGNED',
    TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
    TASK_MARKED_SUSPICIOUS = 'TASK_MARKED_SUSPICIOUS',
    TASK_COMPLETED = 'TASK_COMPLETED',

    // Event actions
    EVENT_UPLOADED = 'EVENT_UPLOADED',
    EVENT_REJECTED_DUPLICATE = 'EVENT_REJECTED_DUPLICATE',
    EVENT_REJECTED_TASK_LOCKED = 'EVENT_REJECTED_TASK_LOCKED',
}

/**
 * Parameters for creating an audit log entry.
 */
export interface CreateAuditLogParams {
    userId?: string | null;
    action: string;
    entityType: string;
    entityId?: string | null;
    ipAddress?: string | null;
}

/**
 * Audit Logs Service.
 * Handles creation and retrieval of audit log entries.
 * 
 * CRITICAL: This service only provides INSERT and SELECT operations.
 * UPDATE and DELETE are intentionally NOT implemented.
 */
@Injectable()
export class AuditLogsService {
    constructor(
        @InjectRepository(AuditLog)
        private readonly auditLogRepository: Repository<AuditLog>,
    ) { }

    /**
     * Create a new audit log entry.
     * Timestamp is generated server-side automatically by TypeORM.
     * 
     * @param params - Audit log parameters
     * @returns Created audit log entry
     */
    async create(params: CreateAuditLogParams): Promise<AuditLog> {
        const auditLog = this.auditLogRepository.create({
            user_id: params.userId ?? null,
            action: params.action,
            entity_type: params.entityType,
            entity_id: params.entityId ?? null,
            ip_address: params.ipAddress ?? null,
            // created_at is auto-generated by TypeORM
        });

        return this.auditLogRepository.save(auditLog);
    }

    /**
     * Convenience method for logging actions with consistent format.
     */
    async log(
        action: AuditAction | string,
        entityType: string,
        entityId: string | null,
        userId: string | null,
        ipAddress: string | null,
    ): Promise<AuditLog> {
        return this.create({
            userId,
            action,
            entityType,
            entityId,
            ipAddress,
        });
    }

    /**
     * Get all audit logs for admin viewing.
     * Results are ordered by created_at descending (newest first).
     * 
     * @param limit - Maximum number of records to return
     * @param offset - Number of records to skip for pagination
     */
    async findAll(limit = 100, offset = 0): Promise<AuditLog[]> {
        return this.auditLogRepository.find({
            order: { created_at: 'DESC' },
            take: limit,
            skip: offset,
        });
    }

    /**
     * Get audit logs for a specific entity.
     */
    async findByEntity(entityType: string, entityId: string): Promise<AuditLog[]> {
        return this.auditLogRepository.find({
            where: { entity_type: entityType, entity_id: entityId },
            order: { created_at: 'DESC' },
        });
    }

    /**
     * Get audit logs for a specific user.
     */
    async findByUser(userId: string): Promise<AuditLog[]> {
        return this.auditLogRepository.find({
            where: { user_id: userId },
            order: { created_at: 'DESC' },
        });
    }
}
