import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    ManyToOne,
    JoinColumn,
} from 'typeorm';
import { Task } from '../../tasks/entities/task.entity';
import { EventType } from '../../shared/enums';

/**
 * TaskEvent entity - IMMUTABLE EVIDENCE TABLE.
 * 
 * ╔══════════════════════════════════════════════════════════════════╗
 * ║  CRITICAL SECURITY RULE:                                         ║
 * ║  Records in this table MUST NEVER be updated or deleted.         ║
 * ║  This is a government-grade audit trail for legal evidence.      ║
 * ╚══════════════════════════════════════════════════════════════════╝
 * 
 * Each event captures:
 * - WHAT: Event type (PICKUP, TRANSIT, FINAL)
 * - WHEN: Server-generated timestamp (never client)
 * - WHERE: GPS coordinates
 * - PROOF: Image with SHA-256 hash for integrity verification
 */
@Entity('task_events')
export class TaskEvent {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    /**
     * Reference to the parent task.
     */
    @Column({ type: 'uuid' })
    task_id: string;

    @ManyToOne(() => Task, { eager: false })
    @JoinColumn({ name: 'task_id' })
    task: Task;

    /**
     * Type of event.
     * RULE: Each event_type can only occur ONCE per task.
     */
    @Column({
        type: 'enum',
        enum: EventType,
    })
    event_type: EventType;

    /**
     * URL/path to the uploaded image.
     * Never expose storage credentials in this field.
     */
    @Column({ type: 'text' })
    image_url: string;

    /**
     * SHA-256 hash of the uploaded image.
     * Used for integrity verification.
     */
    @Column({ type: 'varchar', length: 64 })
    image_hash: string;

    /**
     * GPS latitude at time of event.
     */
    @Column({ type: 'decimal', precision: 10, scale: 7 })
    latitude: number;

    /**
     * GPS longitude at time of event.
     */
    @Column({ type: 'decimal', precision: 10, scale: 7 })
    longitude: number;

    /**
     * SERVER-GENERATED timestamp.
     * ╔═══════════════════════════════════════════════════════════════╗
     * ║  CRITICAL: This timestamp is generated by the server ONLY.    ║
     * ║  Client-provided timestamps are IGNORED.                      ║
     * ╚═══════════════════════════════════════════════════════════════╝
     */
    @Column({ type: 'timestamp' })
    server_timestamp: Date;

    /**
     * Record creation timestamp (same as server_timestamp for new records).
     */
    @CreateDateColumn({ type: 'timestamp' })
    created_at: Date;
}
